### ISSUE TITLE
Compilation errors, Mac OS X Yosemite 10.10.3

### ISSUE THREAD

**Issue by ntedeschi** [b-k/apophenia#22]
Hi,

I am getting the following errors when trying to compile:

../../apophenia-pkg/model/apop_histogram.c:116:21: error: expected expression
    OMP_for_reduce(+:ll,    int i=0; i< datasize; i++){
                    ^
../../apophenia-pkg/apop_internal.h:65:33: note: expanded from macro 'OMP_for_reduce'
#define OMP_for_reduce(...) for(__VA_ARGS__)
                                ^
../../apophenia-pkg/model/apop_histogram.c:116:38: error: use of undeclared identifier 'i'
    OMP_for_reduce(+:ll,    int i=0; i< datasize; i++){
                                     ^
../../apophenia-pkg/apop_internal.h:65:33: note: expanded from macro 'OMP_for_reduce'
#define OMP_for_reduce(...) for(__VA_ARGS__)
                                ^
../../apophenia-pkg/model/apop_histogram.c:116:51: error: use of undeclared identifier 'i'
    OMP_for_reduce(+:ll,    int i=0; i< datasize; i++){

I am able to compile fine on Linux.  Is this a clang issue?  I am using clang-602.0.49, Apple LLVM version 6.1.0.

Thanks,
Neil

**Comment by mcheema** [comment]
download the latest apop_internal.h and then try and compile it should work. I submitted a patch which fixes this error. 
Also, note that OMP is not available in the default OS X compiler.

**Comment by ntedeschi** [comment]
That worked!  Thank you very much for taking the time to address the issue.
