### ISSUE TITLE
Apophenia not available using homebrew (on Mac OSX)

### ISSUE THREAD

**Issue by bdobyns** [b-k/apophenia#31]
This has no formula available so Mac OSX users cannot `brew install apophenia`

I created a pull request https://github.com/Homebrew/homebrew-core/pull/331 (now closed, see below) against the homebrew-core project to build apophenia from scratch.  

But really, that should be part of this project, not something written and maintained by outsiders.

I do observe that there's a [macports portfile](https://trac.macports.org/ticket/50878) as well, apparently maintained outside this project, also.

**Comment by bdobyns** [comment]
well, homebrew suggested that we move it to homebrew-science.  which is sensible.

https://github.com/Homebrew/homebrew-science/pull/3568

**Comment by bdobyns** [comment]
okay.  it finally got accepted over at homebrew/science, so macintosh users can 

```
brew install homebrew/science/apophenia
```

or 

```
brew tap homebrew/science
brew install apophenia
```

**Comment by b-k** [comment]
This is absolutely stellar. I see the install script you've added to the brew repository even passes with `--enable-extended-tests`.

I'll update the documentation to point users to the brew option within the next day.

[PS: I'm happy to maintain the brew script myself if you buy me a mac to do it with (smiley face). ]

**Comment by bdobyns** [comment]
Sadly, I'm fresh out of spare mac computers to hand out.
